/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.FileDialog;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import t1so.backend;

/**
 *
 * @author Jean
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    
    private backend backLogic = null;
    private int countInstructions;
    
    public main() {
        initComponents();
        setLocationRelativeTo(null);
        backLogic =  new backend();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_fileSelected = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_instructions = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        var_DX = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        var_BX = new javax.swing.JLabel();
        var_CX = new javax.swing.JLabel();
        var_AX = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        var_PC = new javax.swing.JLabel();
        var_AC = new javax.swing.JLabel();
        var_IR = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("T1-SO");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_fileSelected.setEditable(false);
        txt_fileSelected.setBackground(new java.awt.Color(255, 255, 255));
        txt_fileSelected.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        txt_fileSelected.setText("No selected file");
        txt_fileSelected.setToolTipText("");
        jPanel1.add(txt_fileSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 68, 310, 35));

        jButton2.setBackground(new java.awt.Color(0, 131, 143));
        jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Next instruction");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 440, 35));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 20)); // NOI18N
        jLabel2.setText("Load File");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tbl_instructions.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbl_instructions.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        tbl_instructions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Instruction", "ASM", "Binary code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_instructions.setFocusable(false);
        tbl_instructions.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_instructions.setSelectionBackground(new java.awt.Color(0, 131, 143));
        tbl_instructions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_instructions.setShowGrid(true);
        tbl_instructions.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_instructions);
        if (tbl_instructions.getColumnModel().getColumnCount() > 0) {
            tbl_instructions.getColumnModel().getColumn(0).setMaxWidth(100);
            tbl_instructions.getColumnModel().getColumn(1).setResizable(false);
            tbl_instructions.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 440, 270));

        jButton3.setBackground(new java.awt.Color(0, 131, 143));
        jButton3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Choose a file");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 68, 110, 35));

        jLabel13.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 20)); // NOI18N
        jLabel13.setText("Memory");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(224, 224, 224));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 440, 10));

        var_DX.setBackground(new java.awt.Color(153, 0, 153));
        var_DX.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        var_DX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var_DX.setText("0");
        jPanel1.add(var_DX, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 110, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("DX");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 110, -1));

        var_BX.setBackground(new java.awt.Color(153, 0, 153));
        var_BX.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        var_BX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var_BX.setText("0");
        jPanel1.add(var_BX, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 110, -1));

        var_CX.setBackground(new java.awt.Color(153, 0, 153));
        var_CX.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        var_CX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var_CX.setText("0");
        jPanel1.add(var_CX, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 110, -1));

        var_AX.setBackground(new java.awt.Color(153, 0, 153));
        var_AX.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        var_AX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var_AX.setText("0");
        jPanel1.add(var_AX, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, -1));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 16)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("CX");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 110, -1));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 16)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("IR");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 146, -1));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 16)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("BX");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 110, -1));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 16)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("AX");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, -1));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 16)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("AC");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 146, -1));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 16)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("PC");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 146, -1));

        var_PC.setBackground(new java.awt.Color(255, 255, 255));
        var_PC.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        var_PC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var_PC.setText("0");
        jPanel1.add(var_PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 146, -1));

        var_AC.setBackground(new java.awt.Color(255, 255, 255));
        var_AC.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        var_AC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var_AC.setText("0");
        jPanel1.add(var_AC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 146, -1));

        var_IR.setBackground(new java.awt.Color(255, 255, 255));
        var_IR.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        var_IR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var_IR.setText("0");
        jPanel1.add(var_IR, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 146, -1));

        jSeparator3.setForeground(new java.awt.Color(224, 224, 224));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 440, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 718));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(countInstructions!=backLogic.getSizeASM()-1){
            countInstructions++;
            selectInstruction();
            backLogic.executeInstruction(tbl_instructions.getModel().getValueAt(tbl_instructions.getSelectedRow(), 2).toString());
            updateVisualVars();
            
        }
        else{
            showMessageDialog(null, "End of file", "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "ASM FILES", "asm", "asm");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            backLogic.setFilePath(chooser.getSelectedFile().getPath());
            backLogic.cleanMemory();
            backLogic.initializeMemory();
            backLogic.readFile();
            if(backLogic.validateFile()){
                clearTable();
                txt_fileSelected.setText(chooser.getSelectedFile().getName());
                loadVisualVars();
            }
            else{
                showMessageDialog(null, "Invalid file", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void clearTable(){
        DefaultTableModel model = (DefaultTableModel) tbl_instructions.getModel();
        if(model.getRowCount()>0){
            int countrows=model.getRowCount();
            for (int i = countrows; i> 0;i--){
                model.removeRow(i-1);
            }
        }
    }
    
    private void loadVisualVars(){
        ArrayList<String>temp= backLogic.getMainMemory();
        ArrayList<String>tempASM=  backLogic.getASM();
        
        var_PC.setText(temp.get(0));
        var_AC.setText(temp.get(1));
        var_IR.setText(temp.get(2));
        
        var_AX.setText(temp.get(3));
        var_BX.setText(temp.get(4));
        var_CX.setText(temp.get(5));
        var_DX.setText(temp.get(6));
        
        
        int sizeOfIsntructions = backLogic.getSizeASM();
        int initPC = Integer.parseInt(temp.get(0)); 
        
        DefaultTableModel model = (DefaultTableModel) tbl_instructions.getModel();
        int cont =0;
        for (int i=initPC; i<sizeOfIsntructions + initPC;i++){
            model.addRow(new Object[]{i,tempASM.get(cont),temp.get(i)});
            cont++;
        }
        tbl_instructions.setModel(model);
        selectInstruction();
        backLogic.executeFirstInstruction(tbl_instructions.getModel().getValueAt(tbl_instructions.getSelectedRow(), 2).toString());
        updateVisualVars();
    }
    
    public void selectInstruction(){
        tbl_instructions.setRowSelectionInterval(countInstructions,countInstructions);   
    }
    
    public void updateVisualVars(){
        ArrayList<String>temp= backLogic.getMainMemory();
    
        var_PC.setText(temp.get(0));
        var_AC.setText(temp.get(1));
        var_IR.setText(temp.get(2));
        
        var_AX.setText(temp.get(3));
        var_BX.setText(temp.get(4));
        var_CX.setText(temp.get(5));
        var_DX.setText(temp.get(6));
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tbl_instructions;
    private javax.swing.JTextField txt_fileSelected;
    private javax.swing.JLabel var_AC;
    private javax.swing.JLabel var_AX;
    private javax.swing.JLabel var_BX;
    private javax.swing.JLabel var_CX;
    private javax.swing.JLabel var_DX;
    private javax.swing.JLabel var_IR;
    private javax.swing.JLabel var_PC;
    // End of variables declaration//GEN-END:variables
}
